#!/usr/bin/env sh
# shellcheck disable=SC2034

# General Icons
ICON_LOADING=􀖇
ICON_APPLE=􀣺
ICON_PREFERENCES=􀺽
ICON_ACTIVITY=􀒓
ICON_LOCK=􀒳
ICON_MAIL=􀍜
ICON_MAIL_OPEN=􀍜
ICON_BELL=􀋚
ICON_BELL_DOT=􀝗
ICON_CALENDAR=􀉉
ICON_CLOCK=􀐫
ICON_RIGHT=􀯻
# 􀆊􀯻
ICON_LEFT=􀆉

# Git Icons
ICON_GIT_ISSUE=􀍷
ICON_GIT_DISCUSSION=􀒤
ICON_GIT_PULL_REQUEST=􀙡
ICON_GIT_COMMIT=􀡚
ICON_GIT_INDICATOR=􀂓

ICON_SPOTIFY= # nerd font
ICON_MUSIC_PLAY=􀊆
ICON_MUSIC_PAUSE=􀊄
ICON_MUSIC_STOP=􀛷
ICON_MUSIC_SHUFFLE=􀊝
ICON_MUSIC_REPEAT=􀊞
ICON_MUSIC_NEXT=􀊐
ICON_MUSIC_PREV=􀊎

# Yabai Icons
ICON_YABAI_STACK=􀏭
ICON_YABAI_FULLSCREEN_ZOOM=􀏜
ICON_YABAI_PARENT_ZOOM=􀥃
ICON_YABAI_FLOAT=􀢌
ICON_YABAI_GRID=􀧍

ICON_CPU=􀫥
ICON_DISK=􀤃
ICON_MEMORY=􀧖
ICON_NETWORK=
# ICON_NETWORK_DOWN=
# ICON_NETWORK_UP=
ICON_NETWORK_DOWN=􀄩
ICON_NETWORK_UP=􀄨
ICON_BRIGHTNESS=􀆮

# speaker
ICON_SPEAKER_0=􀊣
ICON_SPEAKER_1=􀊥
ICON_SPEAKER_2=􀊧
ICON_SPEAKER_3=􀊩
ICON_SPEAKER_ERROR=􀾐
ICON_AIRPODS_PRO=􀪷
# ICON_SPEAKER_0=􀊢
# ICON_SPEAKER_1=􀊤
# ICON_SPEAKER_2=􀊦
# ICON_SPEAKER_3=􀊨
# ICON_SPEAKER_ERROR=􀾏

# battery
ICON_BATTERY_0=􀛪
ICON_BATTERY_25=􀛩
ICON_BATTERY_50=􀺶
ICON_BATTERY_75=􀺸
ICON_BATTERY_100=􀛨
ICON_BATTERY_CHARGING=􀢋
