#!/usr/bin/env bash
# shellcheck disable=SC2034,SC2206

source "$CONFIG_DIR/icons.sh"
source "$CONFIG_DIR/colors.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="Maple Mono"              # Regular
FONT_CODICON="codicon"         # Regular
FONT_NERD="Symbols Nerd Font"  # Regular
FONT_SYMBOL="SF Pro"           # Regular
FONT_MONOSPACE="Iosevka"       # Regular, Italic, Bold, Thin, Medium, Extrabode, Heavy, ...
FONT_APPLE="AppleSymbols"      # Regular
FONT_EMOJI="Apple Color Emoji" # Regular

PADDINGS=3 # All paddings use this value (icon, label, background)

CORNER_RADIUS=15

bar_config=(
    color=$BAR_COLOR
    border_color=$BAR_COLOR
    position=top
    height=30
    margin=12
    y_offset=5
    corner_radius=$CORNER_RADIUS
    border_width=0
    blur_radius=6
    padding_left=3
    padding_right=0
    notch_width=200
    notch_offset=0
    display=all
    hidden=off
    topmost=off
    sticky=on
    font_smoothing=on
    shadow=on
)

default_config=(
    updates=when_shown
    icon.font="$FONT_SYMBOL:Regular:13.0"
    icon.color=$ICON_COLOR
    icon.y_offset=0
    icon.padding_left=$PADDINGS
    icon.padding_right=$PADDINGS
    label.font="$FONT:Regular:13.0"
    label.color=$LABEL_COLOR
    label.padding_left=$PADDINGS
    label.padding_right=$PADDINGS
    background.padding_right=$PADDINGS
    background.padding_left=$PADDINGS
    background.height=26
    background.corner_radius=15
    popup.background.border_width=2
    popup.background.corner_radius=11
    popup.background.border_color=$POPUP_BORDER_COLOR
    popup.background.color=$POPUP_BACKGROUND_COLOR
    popup.background.shadow.drawing=on
)

sketchybar --bar "${bar_config[@]}"
sketchybar --default "${default_config[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/skhd.sh"

# Center
source "$ITEM_DIR/clock.sh"

# Right
source "$ITEM_DIR/system_status.sh"
source "$ITEM_DIR/controlcenter.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/task.sh"
source "$ITEM_DIR/spotify.sh"
sketchybar --add alias "Knock,Item-0" right

#################### Finalizing Setup ####################

sketchybar --update

echo "sketchybar configuration loaded.."

# vim:ft=bash:
