-- sqlite3 yabai.db < create_table.sql
CREATE TABLE IF NOT EXISTS windows (
	id INTEGER,
    pid INTEGER,
    app TEXT,
    title TEXT,
    frame TEXT,
    role TEXT,
    subrole TEXT,
    display INTEGER,
    space INTEGER,
    level INTEGER,
    layer INTEGER,
    opacity REAL,
    split_type TEXT,
    split_child TEXT,
    stack_index INTEGER,
    can_move INTEGER,
    can_resize INTEGER,
    has_focus INTEGER,
    has_shadow INTEGER,
    has_parent_zoom INTEGER,
    has_fullscreen_zoom INTEGER,
    is_native_fullscreen INTEGER,
    is_visible INTEGER,
    is_minimized INTEGER,
    is_hidden INTEGER,
    is_floating INTEGER,
    is_sticky INTEGER,
    is_grabbed INTEGER,
    create_time INTEGER,
    focus_time INTEGER,
    is_destroyed INTEGER
);
