#!/usr/bin/env zsh

WINDOW=$(yabai -m query --windows --window)
if [[ "$(echo "$WINDOW" | jq '.["is-floating"]')" == "true" ]]; then
    yabai -m window --grid 1:1:0:0:1:1
else
    yabai -m window --toggle zoom-fullscreen
fi
sketchybar --trigger window_state_changed
