#!/usr/bin/env zsh

# init
YABAI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/yabai"
if [[ ! -d "$YABAI_DATA" ]]; then
    mkdir -p "$YABAI_DATA"
fi
if [[ ! -f "$YABAI_DATA/yabai.db" ]]; then
    sqlite3 "$YABAI_DATA/yabai.db" <"$HOME/.config/yabai/create_table.sql"
fi
if [[ ! -d "${XDG_CACHE_HOME:-$HOME/.cache}/yabai" ]]; then
    mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/yabai"
fi

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config debug_output off

yabai -m config external_bar all:35:0

yabai -m config layout bsp \
    top_padding 10 \
    bottom_padding 10 \
    left_padding 10 \
    right_padding 10 \
    window_gap 10

yabai -m config \
    focus_follows_mouse off \
    window_origin_display cursor \
    window_zoom_persist on \
    window_shadow on \
    window_opacity on \
    window_opacity_duration 0.0 \
    window_animation_duration 0.1 \
    normal_window_opacity 1.0 \
    active_window_opacity 1.0 \
    split_type auto \
    auto_balance off \
    mouse_modifier ctrl \
    mouse_action1 move \
    mouse_action2 resize

yabai -m rule --add app=".*" sub-layer=normal

# manage off
manage_off_apps="^(OrbStack|预览|系统信息|Raycast|Bezel|活动监视器|Barcode|IINA|便笺|系统设置|Easydict"
manage_off_apps="${manage_off_apps}|Knock|准入客户端|MindMac|PyCharm|Arc"
manage_off_apps="${manage_off_apps}|访达|Omi录屏专家|iStat Menus Status|QuickTime Player|scrcpy)$"
yabai -m rule --add app="${manage_off_apps}" manage=off
yabai -m rule --add subrole="^(AXDialog|AXSystemDialog)$" manage=off
yabai -m rule --add title="打开" manage=off

# layer above, or sticky
layer_above_apps='^(通知中心|Barcode|Snipaste|scrcpy|便笺)$'
yabai -m rule --add app="${layer_above_apps}" sub-layer=above
yabai -m rule --add app="Omi录屏专家" title="文件列表" sub-layer=above sticky=on
yabai -m rule --add app="Omi录屏专家" title="已选择1个窗口" sub-layer=above
yabai -m rule --add app="Omi录屏专家" title="已选择1个App" sub-layer=above
yabai -m rule --add app="QuickTime Player" sticky=on
yabai -m rule --add app="Bezel" sticky=on sub-layer=below
yabai -m rule --add app="Hammerspoon" subrole="AXDialog" sub-layer=above sticky=on

# signal
app_ignore='^(通知中心|控制中心|iStat Menus Status)$'

# yabai -m signal --add event=window_created     action='$HOME/.config/yabai/helper.sh window_created     $YABAI_WINDOW_ID' app!="$app_ignore"
# yabai -m signal --add event=window_focused     action='$HOME/.config/yabai/helper.sh window_focused     $YABAI_WINDOW_ID' app!="$app_ignore"
# yabai -m signal --add event=window_resized     action='$HOME/.config/yabai/helper.sh window_resized     $YABAI_WINDOW_ID' app!="$app_ignore"
# yabai -m signal --add event=window_minimized   action='$HOME/.config/yabai/helper.sh window_minimized   $YABAI_WINDOW_ID' app!="$app_ignore"
# yabai -m signal --add event=window_deminimized action='$HOME/.config/yabai/helper.sh window_deminimized $YABAI_WINDOW_ID' app!="$app_ignore"
# yabai -m signal --add event=window_destroyed   action='$HOME/.config/yabai/helper.sh window_destroyed   $YABAI_WINDOW_ID' app!="$app_ignore"

yabai -m signal --add event=window_created     action='eval "$(luarocks path --bin)";lua $HOME/.config/yabai/helper.lua window_created     $YABAI_WINDOW_ID' app!="$app_ignore"
yabai -m signal --add event=window_focused     action='eval "$(luarocks path --bin)";lua $HOME/.config/yabai/helper.lua window_focused     $YABAI_WINDOW_ID' app!="$app_ignore"
yabai -m signal --add event=window_resized     action='eval "$(luarocks path --bin)";lua $HOME/.config/yabai/helper.lua window_resized     $YABAI_WINDOW_ID' app!="$app_ignore"
yabai -m signal --add event=window_minimized   action='eval "$(luarocks path --bin)";lua $HOME/.config/yabai/helper.lua window_minimized   $YABAI_WINDOW_ID' app!="$app_ignore"
yabai -m signal --add event=window_deminimized action='eval "$(luarocks path --bin)";lua $HOME/.config/yabai/helper.lua window_deminimized $YABAI_WINDOW_ID' app!="$app_ignore"
yabai -m signal --add event=window_destroyed   action='eval "$(luarocks path --bin)";lua $HOME/.config/yabai/helper.lua window_destroyed   $YABAI_WINDOW_ID' app!="$app_ignore"

# yabai -m signal --add event=display_changed action="hs -c 'local cscreen = hs.window.focusedWindow():screen();local fframe = cscreen:fullFrame();local cursor_screen = hs.mouse.getCurrentScreen();if cursor_screen:id() ~= cscreen:id() then hs.mouse.setRelativePosition({x=fframe.w/2, y=fframe.h/2}, cscreen); end'"

# vim:ft=bash:
